version: '3.7'

services:
  app:
    image: node:latest
    ports:
      - $PORT:$PORT
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
